- name: Check if binary already exists in $PATH
  ansible.builtin.shell: 'command -v {{ shellcheck_bin }}'
  register: shellcheck_bin_exists
  ignore_errors: true
  changed_when: false

- name: Get installed version if any
  ansible.builtin.shell: shellcheck --version | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+"
  register: _check_shellcheck_v_task
  ignore_errors: true
  changed_when: false

- name: Register preflight facts
  ansible.builtin.set_fact:
    installed_shellcheck_v: "{{ _check_shellcheck_v_task.stdout | default('0.0.0', true) }}"

- name: Displaying current version
  ansible.builtin.debug:
    msg: 'Current version: {{ installed_shellcheck_v if _check_shellcheck_v_task is success else "Not Installed" }}'
