- name: Preflight preparation
  ansible.builtin.include_tasks: preflight.yaml
  tags:
  - always

- name: Install Bob from release archive
  ansible.builtin.include_tasks: bob.yaml
  when:
  - _nvim_bob_nov is version(_installed_nvim_bob_v, 'ne')
  - not nvim_bob_brew

- name: MacOS homebrew installation
  ansible.builtin.include_tasks: brew.yaml
  when:
  - nvim_bob_brew
  - ansible_facts["system"] == 'Darwin'

- name: Neovim configuration deploy from git repo
  ansible.builtin.include_tasks: config.yaml
  when:
  - neovim_config_deploy
  - neovim_config_repo | default('', true) | trim != ''
