- name: Preflight preparation
  ansible.builtin.include_tasks: preflight.yaml
  tags:
  - always

- name: Install Bob from release archive
  ansible.builtin.include_tasks: bob.yaml
  when:
  - _nvim_bob_nov is version(_installed_nvim_bob_v, 'ne')

- name: Neovim configuration deploy from git repo
  ansible.builtin.include_tasks: config.yaml
  when:
  - neovim_config_deploy
  - neovim_config_repo | default('', true) | trim != ''
