eza_v: v0.23.4

# Provide checksum for downloaded archive to verify integrity
# Found on the Github Release page
eza_archive_checksum:

eza_musl: false

_eza_nov: "{{ eza_v | regex_replace('^v', '') }}"

_eza_arch_map:
  x86_64: x86_64
  aarch64: aarch64

_eza_sys_map:
  Linux: unknown-linux
  # no releases for darwin
  # Darwin: apple-darwin

_eza_arch: "{{ _eza_arch_map[ansible_facts.architecture] }}"
_eza_sys: "{{ _eza_sys_map[ansible_facts.system] }}"

_eza_release_base_url: https://github.com/eza-community/eza/releases/download/v{{ _eza_nov }}
_eza_release_archive_name: eza_{{ _eza_arch }}-{{ _eza_sys }}{{ '-musl' if eza_musl else '-gnu' }}.tar.gz
eza_release_url: "{{ _eza_release_base_url }}/{{ _eza_release_archive_name }}"

eza_archive_download_dst: /tmp
eza_extraction_path: '{{ eza_archive_download_dst }}/eza-{{ _eza_nov }}'
eza_cleanup_release_artifacts: true

eza_bin: eza
# eza_bin_dst: /usr/local/bin
# tools_bin_dst: /usr/local/bin
eza_bin_dst_default: /usr/local/bin
eza_bin_dst_effective: >-
  {{ (eza_bin_dst | default(tools_bin_dst | default(eza_bin_dst_default))) }}

eza_deploy_man: true
eza_man_url: '{{ _eza_release_base_url }}/man-{{ _eza_nov }}.tar.gz'
man_base_path: /usr/share/man

eza_deploy_completions: false
eza_competions_url: '{{ _eza_release_base_url }}/completions-{{ _eza_nov }}.tar.gz'
bash_completions_path: /usr/share/bash-completion/completions
zsh_completions_path: /usr/share/zsh/site-functions
fish_completions_path: /usr/share/fish/vendor_completions.d
