- name: Get currently installed version if any
  ansible.builtin.shell: taplo --version | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+"
  register: _check_taplo_version_task
  ignore_errors: true
  changed_when: false

- name: Setting version facts
  ansible.builtin.set_fact:
    _installed_taplo_v: "{{ _check_taplo_version_task.stdout | default('0.0.0', true) }}"

- name: Reporting installed version
  ansible.builtin.debug:
    msg: 'Installed version: {{ _installed_taplo_v if _check_taplo_version_task is success else "Not Found" }}'
