- name: Installing kube-ps1 from GitHub
  ansible.builtin.get_url:
    url: '{{ kubeps1_release_url }}'
    dest: '{{ kubeps1_bin_dst }}/{{ kubeps1_bin }}'
    force: '{{ kubeps1_force_reinstall }}'
  when:
  - not kubeps1_brew

- name: Brew install kube-ps1
  community.general.homebrew:
    name: '{{ kubeps1_brew_package }}'
    state: '{{ kubeps1_brew_state }}'
    update_homebrew: true
  when:
  - kubeps1_brew
  - ansible_facts.system == 'Darwin'

- name: Instructions
  ansible.builtin.debug:
    msg: |
      To activate kube-ps1.sh

      Zsh:
          source /path/to/kube-ps1.sh
          PROMPT='$(kube_ps1)'$PROMPT # or RPROMPT='$(kube_ps1)'

      Bash:
          source /path/to/kube-ps1.sh
          PS1='[\u@\h \W $(kube_ps1)]\$ '

      For more information, visit https://github.com/jonmosco/kube-ps1
