- name: Check if binary already exists in $PATH
  ansible.builtin.command: command -v {{ shfmt_bin }}
  register: __shfmt_bin_exists
  ignore_errors: true
  changed_when: false

- name: Get installed version if any
  ansible.builtin.shell: '{{ shfmt_bin }} --version | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+"'
  register: __check_shfmt_v_task
  ignore_errors: true
  changed_when: false

- name: Register installed version vars
  ansible.builtin.set_fact:
    __installed_shfmt_v: "{{ __check_shfmt_v_task.stdout | default('0.0.0', true) }}"

- name: Displaying installed version
  ansible.builtin.debug:
    msg: |
      Installed version: {{ __installed_shfmt_v if __check_shfmt_v_task is success else "Not Found" }}
