- name: Check if binary already exists in $PATH
  ansible.builtin.shell: 'command -v {{ prek_bin }}'
  register: _prek_bin_exists
  ignore_errors: true
  changed_when: false

- name: Get installed version if any
  ansible.builtin.shell: prek --version | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+"
  register: _check_prek_v_task
  ignore_errors: true
  changed_when: false

- name: Register pre-flight variables
  ansible.builtin.set_fact:
    _installed_prek_v: "{{ _check_prek_v_task.stdout | default('0.0.0', true) }}"

- name: Reporting installed version
  ansible.builtin.debug:
    msg: 'Installed version: {{ _installed_prek_v if _check_prek_v_task is success else "Not Found" }}'
