argonaut_v: v2.6.1

_argonaut_nov: "{{ argonaut_v | regex_replace('^v', '') }}"

_argonaut_sys_map:
  Darwin: darwin
  Linux: linux

_argonaut_arch_map:
  x86_64: amd64
  aarch64: arm64

_argonaut_sys: "{{ _argonaut_sys_map[ansible_facts.system] }}"
_argonaut_arch: "{{ _argonaut_arch_map[ansible_facts.architecture] }}"

argonaut_release_base_url: https://github.com/darksworm/argonaut/releases/download/v{{ _argonaut_nov }}
argonaut_release_artifact_name: argonaut-{{ _argonaut_nov }}-{{ _argonaut_sys }}-{{ _argonaut_arch }}.tar.gz
argonaut_release_url: "{{ argonaut_release_base_url }}/{{ argonaut_release_artifact_name }}"

argonaut_checksum_verify: false
argonaut_checksum_url: "{{ argonaut_release_base_url }}/checksums.txt"

argonaut_archive_download_dst: /tmp
argonaut_extract_dst: '{{ argonaut_archive_download_dst }}/argonaut-{{ _argonaut_nov }}'

argonaut_bin_dst: /usr/local/bin
argonaut_bin: argonaut

argonaut_brew: false
argonaut_brew_add_tap: true
argonaut_brew_tap: darksworm/homebrew-tap
argonaut_brew_package: argonaut
argonaut_brew_state: latest
