- name: Preflight preparation
  ansible.builtin.include_tasks: preflight.yaml
  tags:
  - always

- name: MacOS homebrew installation
  ansible.builtin.include_tasks: brew.yaml
  when:
  - chezmoi_brew
  - ansible_facts.os_family == "Darwin"

- name: Get checksum
  ansible.builtin.include_tasks: checksums.yaml
  when:
  - chezmoi_checksum_verify
  - not chezmoi_brew

- name: Install chezmoi release archive
  ansible.builtin.include_tasks: release_archive.yaml
  when:
  - chezmoi_install_archive
  - not chezmoi_install_binary
  - not chezmoi_install_package
  - not chezmoi_brew

- name: Install chezmoi binary
  ansible.builtin.include_tasks: release_binary.yaml
  when:
  - chezmoi_install_binary
  - not chezmoi_install_archive
  - not chezmoi_install_package
  - not chezmoi_brew

- name: Install chezmoi release OS package
  ansible.builtin.include_tasks: release_package.yaml
  when:
  - chezmoi_install_package
  - not chezmoi_install_archive
  - not chezmoi_install_binary
  - not chezmoi_brew
