- name: Install python compilation dependencies on a Debian based OS
  ansible.builtin.apt:
    name: "{{ python_build_deps }}"
    state: present
    update_cache: true
  become: true
  when: ansible_facts.os_family == "Debian"

- name: Install python compilation dependencies on a RedHat based OS
  ansible.builtin.dnf:
    name: "{{ python_build_deps }}"
    state: present
    update_cache: true
  become: true
  when: ansible_facts.os_family == "RedHat"

- name: Install DNF dependencies for building python on Fedora
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop:
  - gdbm-devel
  - bluez-libs-devel
  - tix-devel
  - libuuid-devel
  when:
  - ansible_facts.os_family == "RedHat"
  - ansible_facts.distribution == "Fedora"
