- name: Check if binary already exists in $PATH
  ansible.builtin.shell: 'command -v {{ ty_bin }}'
  register: ty_bin_exists
  ignore_errors: true
  changed_when: false

- name: Get installed version if any
  ansible.builtin.shell: ty --version | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+"
  register: _check_ty_v_task
  ignore_errors: true
  changed_when: false

- name: Register pre-flight variables
  ansible.builtin.set_fact:
    _installed_ty_v: "{{ _check_ty_v_task.stdout | default('0.0.0', true) }}"

- name: Reporting installed version
  ansible.builtin.debug:
    msg: 'Installed version: {{ _installed_ty_v if _check_ty_v_task is success else "Not Found" }}'

- name: Check completions destinations
  when: ty_deploy_completions
  block:

  - name: Check if Bash completions path exists
    ansible.builtin.stat:
      path: "{{ bash_completions_path }}"
    register: _bash_completions_dst_check

  - name: Check if ZSH completions path exists
    ansible.builtin.stat:
      path: "{{ zsh_completions_path }}"
    register: _zsh_completions_dst_check

  - name: Check if Fish completions path exists
    ansible.builtin.stat:
      path: "{{ fish_completions_path }}"
    register: _fish_completions_dst_check
