kubefwd_v: v1.24.0

_kubefwd_nov: "{{ kubefwd_v | regex_replace('^v', '') }}"

_kubefwd_arch_map:
  x86_64: x86_64
  i386: i386
  aarch64: arm64

_kubefwd_arch: "{{ _kubefwd_arch_map[ansible_facts.architecture] }}"

kubefwd_release_base_url: https://github.com/txn2/kubefwd/releases/download/v{{ _kubefwd_nov }}
kubefwd_archive_url: "{{ kubefwd_release_base_url }}/kubefwd_{{ ansible_facts.system }}_{{ _kubefwd_arch }}.tar.gz"

kubefwd_full_download_path: /tmp/kubefwd_{{ _kubefwd_nov }}

kubefwd_bin_dst: /usr/local/bin
kubefwd_bin: kubefwd

kubefwd_cleanup: true
