kubefwd_v: v1.25.12

_kubefwd_nov: "{{ kubefwd_v | regex_replace('^v', '') }}"

_kubefwd_arch_map:
  x86_64: x86_64
  i386: i386
  aarch64: arm64

_kubefwd_arch: "{{ _kubefwd_arch_map[ansible_facts.architecture] }}"

kubefwd_release_base_url: https://github.com/txn2/kubefwd/releases/download/v{{ _kubefwd_nov }}
kubefwd_release_archive_name: kubefwd_{{ ansible_facts.system }}_{{ _kubefwd_arch }}.tar.gz
kubefwd_release_url: "{{ kubefwd_release_base_url }}/{{ kubefwd_release_archive_name }}"

kubefwd_archive_download_dst: /tmp
kubefwd_extraction_path: '{{ kubefwd_archive_download_dst }}/kubefwd-{{ _kubefwd_nov }}'

kubefwd_checksum_verify: false
kubefwd_checksums_url: '{{ kubefwd_release_base_url }}/kubefwd_checksums.txt'

kubefwd_bin: kubefwd
# kubefwd_bin_dst: /usr/local/bin
# tools_bin_dst: /usr/local/bin
kubefwd_bin_dst_default: /usr/local/bin
kubefwd_bin_dst_effective: >-
  {{ (kubefwd_bin_dst | default(tools_bin_dst | default(kubefwd_bin_dst_default))) }}

kubefwd_cleanup: true
