- name: Check if binary already exists in $PATH
  ansible.builtin.shell: command -v {{ tmux_bin }}
  register: _task_check_path_bin
  ignore_errors: true
  changed_when: false

- name: Get installed version if any
  ansible.builtin.shell: tmux -V | grep -E -o "[0-9]+\.[0-9]+[a-b]?"
  register: _check_tmux_v_task
  ignore_errors: true
  changed_when: false

- name: Register preflight facts
  ansible.builtin.set_fact:
    _installed_tmux_v: "{{ _check_tmux_v_task.stdout | default('0.0a', true) | ansible.builtin.string }}"

- name: Reporting installed version
  ansible.builtin.debug:
    msg: |-
      Installed version: {{ _installed_tmux_v if _check_tmux_v_task is success else "Not Found" }}
