- name: Add argonaut homewbrew tap
  community.general.homebrew_tap:
    name: '{{ argonaut_brew_tap }}'
    state: present
  when: argonaut_brew_add_tap

- name: Brew install
  community.general.homebrew:
    name: '{{ argonaut_brew_package }}'
    state: '{{ argonaut_brew_state }}'
    update_homebrew: true
