- name: Preflight preparation
  ansible.builtin.include_tasks: preflight.yaml
  tags:
  - always

- name: Installation release artifact
  ansible.builtin.include_tasks: release.yaml
  when:
  - _argonaut_nov is version(installed_argonaut_v, 'ne')
