- name: Check if binary already exists
  ansible.builtin.shell: 'command -v {{ argonaut_bin }}'
  register: _check_argonaut_bin_exists
  ignore_errors: true
  changed_when: false

- name: Get installed version if any
  ansible.builtin.shell: argonaut --version | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+"
  register: _check_argonaut_v_task
  ignore_errors: true
  changed_when: false

- name: Registering pre-flight vars
  ansible.builtin.set_fact:
    installed_argonaut_v: "{{ _check_argonaut_v_task.stdout | default('0.0.0', true) }}"

- name: Reporting installed version
  ansible.builtin.debug:
    msg: 'Installed version: {{ installed_argonaut_v if _check_argonaut_v_task is success else "Not Found" }}'
