- name: Check if binary already exists in $PATH
  ansible.builtin.shell: 'command -v {{ age_bin }}'
  register: age_bin_exists
  ignore_errors: true
  changed_when: false

- name: Get installed version if any
  ansible.builtin.shell: age --version | grep -E -o "v[0-9]+\.[0-9]+\.[0-9]+"
  register: _check_age_v_task
  ignore_errors: true
  changed_when: false

- name: Register preflight facts
  ansible.builtin.set_fact:
    _installed_age_v: "{{ _check_age_v_task.stdout | default('v0.0.0', true) }}"

- name: Displaying current version
  ansible.builtin.debug:
    msg: 'Current version: {{ _installed_age_v if _check_age_v_task is success else "Not Installed" }}'
