- name: Check if binary already exists in $PATH
  ansible.builtin.shell: command -v {{ crane_bin }}
  register: _crane_bin_exists
  ignore_errors: true
  changed_when: false

- name: Get installed version if any
  ansible.builtin.shell: crane version | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+"
  register: _check_crane_v_task
  ignore_errors: true
  changed_when: false

- name: Register preflight facts
  ansible.builtin.set_fact:
    _installed_crane_v: "{{ _check_crane_v_task.stdout | default('0.0.0', true) }}"

- name: Reporting current version
  ansible.builtin.debug:
    msg: |-
      Installed version: {{ _installed_crane_v if _check_crane_v_task is success else "Not Found" }}
